# Generated by Django 4.2.13 on 2024-06-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbell_classes', '0002_barbellclass_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barbellclass',
            old_name='content',
            new_name='description',
        ),
        migrations.AddField(
            model_name='barbellclass',
            name='date',
            field=models.DateTimeField(default='10-06-2024 00:00:00'),
        ),
        migrations.AddField(
            model_name='barbellclass',
            name='difficulty',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='barbellclass',
            name='duration',
            field=models.TextField(default=''),
        ),
    ]
