# Generated by Django 4.2.13 on 2024-06-06 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('barbell_classes', '0003_rename_content_barbellclass_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbellclass',
            name='date',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enrolled', models.DateTimeField(auto_now_add=True)),
                ('barbell_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbell_classes.barbellclass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
