# Generated by Django 4.2.13 on 2024-06-07 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('barbell_classes', '0004_alter_barbellclass_date_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbellclass',
            name='available_spots',
            field=models.IntegerField(default=0, help_text='Number of available spots'),
        ),
        migrations.AlterField(
            model_name='barbellclass',
            name='date',
            field=models.TextField(help_text="Enter the date and time of the class (e.g., '2024-06-15 10:00 AM')"),
        ),
        migrations.AlterField(
            model_name='barbellclass',
            name='description',
            field=models.TextField(help_text='Provide a detailed description of the class'),
        ),
        migrations.AlterField(
            model_name='barbellclass',
            name='difficulty',
            field=models.TextField(default='', help_text="Enter the difficulty level of the class (e.g., 'Beginner', 'Intermediate', 'Advanced')"),
        ),
        migrations.AlterField(
            model_name='barbellclass',
            name='duration',
            field=models.TextField(default='', help_text="Enter the duration of the class (e.g., '1 hour')"),
        ),
        migrations.AlterField(
            model_name='barbellclass',
            name='title',
            field=models.CharField(help_text="Enter the title of the barbell class (e.g., 'Beginner Strength Training')", max_length=100),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
