# Generated by Django 4.2.13 on 2024-06-16 01:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('barbell_classes', '0006_remove_barbellclass_date_barbellclass_class_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barbellclass',
            options={'verbose_name': 'Barbell Class', 'verbose_name_plural': 'Barbell Classes'},
        ),
        migrations.AlterField(
            model_name='barbellclass',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='barbellclass',
            name='difficulty',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', help_text='Select the difficulty level of the class', max_length=20),
        ),
    ]
